Feature
akitoshi-m/sample_app_for_rspec pull request #2
Opened 2020-04-21 16:32 UTC by Toshimatu

## 概要

・RSpecとFactoryBotは前回の課題で入れた
・Taskファクトリを作成
・Taskモデルのバリデーションに対してテストを作成
・FactoryBotで作成するデータにnilは入れられなかったので、存在しないことを確認するテストにはFactoryBotを使用しませんでした
・factory_botの設定を行い、クラスメソッドを省略しました。
・「項目に過不足がないデータはバリデーションエラーとならずに正常に作成できること」のテストケースを追加しました

## 確認方法

$ bundle exec rspec を実行して、作成した3つのテストがパスすることを確認ください

## コメント

FactoryBotにnilのデータが入らず苦戦しました。
悩んだ原因としてはcreateメソッドがデータベースに登録しようとするメソッドと把握しておらず、バリデーションに引っかかっていることを把握できていなかったこと。
rails cで登録を試してみて気づきました。
今後rails cを上手に使っていく。

## テスト実施結果

![image](https://user-images.githubusercontent.com/52368204/79889430-f748cd80-8438-11ea-92ea-9e872414c670.png)

2020-04-22 02:21 UTC, yuji91 requested changes

2020-04-22 02:21 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status { 'doing' }
`'doing'`はStringですよね？Symbolとはどのような形式ですか？

2020-04-22 02:21 UTC, yuji91 commented on spec/models/task_spec.rb
> +    task
30行目がなくても31行目で5行目に定義した処理が実行されるので確認してください。。

2020-04-22 02:21 UTC, yuji91 commented on spec/models/task_spec.rb
> +    task.invalid?
この`invalid?`の結果が`false`であることは`expect`として確認しなくても大丈夫ですか？
```suggestion
    expect(task).to be_valid
```

2020-04-22 02:21 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task.errors[:status]).to include()
`include()`だと引数に値がないので何を確認しているかが分かりづらく、記載漏れかという印象もあります。
`be_empty`などの意図が分かりやすいマッチャを使って他の人に分かりやすいように実装してください。

2020-04-22 02:21 UTC, yuji91 commented on spec/models/task_spec.rb
> +    task.invalid?
この行を10行目と同じように記載しないのは何か理由がありますか？

2020-04-22 10:27 UTC, Toshimatu commented on spec/factories/tasks.rb
> +    status { 'doing' }
701d995 にて修正しました。
Symbolは「:foo」のようにコロンで始まる値の表現方法です。
間違えていました。

2020-04-22 10:51 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    task
確認いたしました！taskと書いておいて一度定義をするのかなと思っていたのですが、必要ないとわかりました！
以降のコミットで修正しています。

2020-04-22 10:53 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task.errors[:status]).to include()
5b028c7 にて修正しました。

・be_invalid　→無効であること
・be_valid　　→有効であること
・be_empty　→空であること
を意味するマッチャであることを知りました。

2020-04-22 10:54 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    task.invalid?
6b4751e にて修正しました。
見落としでした。

2020-04-22 10:55 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    task.invalid?
5b028c7 にて修正しました。

2020-04-22 13:38 UTC, yuji91 requested changes
指摘事項についてはレビュー前に確認作業を挟むことで手戻りを減らせると思います。
修正漏れやエラーメッセージの削除について気付けなかった理由を自分で検討してください。

レビュー依頼前にファイル差分と修正に対応するコミットが問題ないかを確認する工程を追加してください。

2020-04-22 13:38 UTC, yuji91 commented on spec/factories/tasks.rb
> +    status { 'doing' }
指摘している3行目の部分がまだ修正されていません。

2020-04-22 13:38 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
ここもエラーメッセージの確認を削除した理由はありますか？

2020-04-22 13:38 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
ここでエラーメッセージの確認を削除した理由はありますか？

2020-04-22 13:38 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task.errors[:status]).to be_empty
`expect(task.errors).to be_empty`だけで良い気がします。

2020-04-22 15:26 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
エラーメッセージの確認を削除した理由は、マッチャであるbe_invalidで無効であることのテストが実行できていると考えたからです。
参考にした記事は以下になります。エラーメッセージの確認コードも書いた方がテストコードとしてよくなりますでしょうか。
https://qiita.com/izumin5210/items/a7036093c25c42f2298d

2020-04-22 15:33 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task.errors[:status]).to be_empty
各カラムに対して1つずつ空の確認は確かに冗長っぽいですね。

2020-04-22 15:33 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
https://github.com/Toshimatu/sample_app_for_rspec/pull/2#discussion_r413081712
こちらと同じ理由です。

2020-04-22 15:35 UTC, akitoshi-m commented on spec/factories/tasks.rb
> +    status { 'doing' }
74ada11 こちらにて修正しました。
ファイル変更を正確にみれていなかったことで見落としていました。

2020-04-22 15:40 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task.errors[:status]).to be_empty
e3b92f3 にて修正しました。

2020-04-22 15:46 UTC, Toshimatu commented
■修正漏れやエラーメッセージの削除について気付けなかった理由
・Conversationのページのみ確認していてFile changesのページをみていなかったから
・修正するべき点に対してのコミットを作れていなかったこと
・エラーメッセージの削除に関しては認識がなかったため

＞改善
・修正を行ったあと、ConversationとFile changesをみて修正ミスや未修正がないかを確認すること
・１つの修正に対して的確にコミットをあげること
・知識不足のため、知識のすり合わせと勉強を重ねていく

2020-04-23 00:34 UTC, yuji91 commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
> エラーメッセージの確認を削除した理由は、マッチャであるbe_invalidで無効であることのテストが実行できていると考えたからです。
この意図がある場合はコミットの単位を分けてレビュアーに伝わるようにしてください。

> 参考にした記事は以下になります。エラーメッセージの確認コードも書いた方がテストコードとしてよくなりますでしょうか。
Qiitaの記事をリファレンスとして出すのは良いですが、どのような意図でそれが行われているのかも検討した方がいいと思います。単にQiitaの記事と同じ書き方、で本当に問題ないでしょうか？
今回のケースであれば、Validationエラーが起きていればテストが通りますが、エラーメッセージの確認を省略するとそれが`precense: true`のエラーなのか`uniqueness: true`のエラーなのか分からないと思います。そこまで確認しないのにテストケースとして挙げている`it`の内容の確認は十分ですか？

2020-04-23 00:36 UTC, yuji91 commented
細かいですが、修正確認のアクションに対してすべてスタンプで返答する必要はないですよ。
![image](https://user-images.githubusercontent.com/28836274/80046526-cf935b80-8545-11ea-9393-7b0c33930fc7.png)

2020-04-23 00:38 UTC, yuji91 requested changes
振り返りと改善のサイクルの実施と、アウトプットをお願いします。

2020-04-23 11:56 UTC, Toshimatu commented on spec/models/task_spec.rb
> +    expect(task).to be_invalid
99cdc86 にて修正を入れました。
・コミットメッセージで修正の意図が伝わるように意識していきます。

テストを実行してパスしたため、be_invalid のみで問題ないだろうと思い、エラーメッセージが格納されていることをテストするコードを削除していました。そのときはこのテスト自体の目的を考えられていなかったことが原因でした。
テストしたい内容に対するコードがかけているか確認を挟みます。

2020-04-23 12:03 UTC, Toshimatu commented
■テストコード作成する際に気をつけること
・テストしたい内容に関してコードが対応しているかを確認すること
・テストがパスしてもそれだけで十分なテストが書けているわけではない
・冗長を避ける（今回でいうとtaskと一行使って置いておく必要はなかった）→経験を重ねていく

■その他
・コミットはレビュワーに伝わりやすいように、修正箇所ごとに細かくする、わかりやすい説明を意識する
・レビュー依頼前にファイルをチェックし、見落としがないか、レビューしやすいかを確認し依頼を投げる

2020-04-24 13:04 UTC, yuji91 approved these changes
`# titleが存在しなければ無効であること`のテストケースにエラーメッセージ確認の`expect`を追加したらマージしてください！

2020-04-24 13:05 UTC, yuji91 commented
特にこの2点が非常に重要です
・テストがパスしてもそれだけで十分なテストが書けているわけではない
・レビュー依頼前にファイルをチェックし、見落としがないか、レビューしやすいかを確認し依頼を投げる

2020-04-25 00:18 UTC, merged