応用課題16 systemspecの作成
akitoshi-m/sample_app_for_rspec pull request #3
Opened 2020-04-26 05:13 UTC by Toshimatu

## 概要

## 行ったこと

[正常系のテスト]
[] ユーザーの新規作成、編集ができること
[] ログインが成功すること
[] ログインした状態でタスクの新規作成、編集、削除ができること
[] マイページにユーザーが新規作成したタスクが表示されること

[] 「ログイン・ユーザー新規登録の成功時に対応するフラッシュメッセージが表示されること」
[] 「タスクの新規作成・編集・削除が成功した場合、対応するフラッシュメッセージと更新したデータが画面上に表示されていること」

[異常系のテスト]
[] メールアドレスが未入力時にユーザーの新規作成、編集が失敗すること
[] 登録済メールアドレス使用時にユーザーの新規作成、編集が失敗すること
[] フォーム未入力時にログインが失敗すること
[] ログインしていないユーザーでタスクの新規作成、編集、マイページへの遷移ができないこと
[] 他のユーザーのユーザー編集、タスク編集ページへの遷移ができないこと

[] 「ログイン・ユーザー新規登録の失敗時に対応するフラッシュメッセージが表示されること」
[] 「タスクの新規作成・編集が失敗した場合、対応するフラッシュメッセージと更新しようとしたデータが画面上に表示されていないこと」

[共通の確認観点]
[] 「処理後の遷移先のパスがどこか」を確認

[その他の要件]
[] 各Controller毎にsystem specを作成し、確認対象の画面毎にdescribeを作成
[] loginメソッドはmoduleを作成し、specファイル間で共通に呼び出す
[] spec実行時にブラウザの表示有無を切り替える設定を spec/support 以下に追加
[] 実行されるテストケースを限定できる設定を spec_helper.rb の50行目辺りを確認して有効化

2020-04-26 08:06 UTC, Toshimatu commented
![image](https://user-images.githubusercontent.com/52368204/80301609-fcfb3600-87df-11ea-8b79-817c5f683b0c.png)

![image](https://user-images.githubusercontent.com/52368204/80301645-2fa52e80-87e0-11ea-85eb-96578fa15b68.png)

![image](https://user-images.githubusercontent.com/52368204/80301654-3e8be100-87e0-11ea-8f5c-d6a49c7625a3.png)

2020-04-26 09:17 UTC, yuji91 commented on spec/system/users_spec.rb
> +    end
1行ならワンライナーで書けます
```suggestion
    before { log_in }
```

2020-04-29 01:06 UTC, yuji91 requested changes

2020-04-29 01:06 UTC, yuji91 commented on spec/system/tasks_spec.rb
> +          select 'todo', from: 'Status'
Symbolで動作しないかどうか確認お願いします。
```suggestion
          select :todo, from: 'Status'
```

2020-04-29 01:26 UTC, Toshimatu commented on spec/system/tasks_spec.rb
> +          select 'todo', from: 'Status'
0d056f0 にて修正しました。

![image](https://user-images.githubusercontent.com/52368204/80553094-96eef880-8a03-11ea-9167-f59a1db6a215.png)

2020-04-29 01:52 UTC, yuji91 approved these changes

2020-04-29 02:23 UTC, merged